### ISSUE TITLE
It doesn't present the lastest version.

### ISSUE THREAD

**Issue by YujiaCheng1996** [egomobile/node-swagger-proxy#1]
Present the same old version as it started with each time I request.
Combine the latest versions from the urls makes more sense.

**Comment by ghost** [comment]
@YujiaCheng1996 

have you tried out [onSourceError setting](https://egomobile.github.io/node-swagger-proxy/interfaces/ISetupSwaggerProxyOptions.html#onSourceError) to figure out if there is an error on source side?

**Comment by YujiaCheng1996** [comment]
It only access the sources once when request the json file for the first time.
1.prepared 2 jsons and run http-server locally.
2.run with the same configurations as example except:
  ```
  sources: [
      {
        url: "http://127.0.0.1:8080/1.json",
      },
      {
        url: "http://127.0.0.1:8080/2.json",
      },
    ],
    onSourceError: (error) => {
      console.log(error);
    },
...
await app.listen(8999);
```
3.request http://localhost:8999/swagger/json multiple times.
Only 2 logs in http-server:
```
[2022-08-19T07:07:03.377Z]  "GET /1.json" "undefined"
(node:3712) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[2022-08-19T07:07:03.397Z]  "GET /2.json" "undefined"
```

No other errors.

**Comment by ghost** [comment]
@YujiaCheng1996 

with version `^0.6.0` you can set `false` to `cache` prop of [ISetupSwaggerProxyOptions interface](https://egomobile.github.io/node-swagger-proxy/interfaces/ISetupSwaggerProxyOptions.html#cache)

```typescript
setupSwaggerProxy(app, {
    //👇
    "cache": false,

    "baseDocument": {
        "info": {
            "title": "My merged API",
            "version": "1.0.0"
        }
    },

    "sources": [
        {
            "url": "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/link-example.json"
        },
        {
            "url": "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/callback-example.yaml"
        },
        {
            "url": "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml"
        }
    ]
})
```

If you need a more complex logic, you can implement an own class/object using [ICache interface](https://egomobile.github.io/node-swagger-proxy/interfaces/ICache.html), which can be submitted to that prop

have a look at [classes folder](https://github.com/egomobile/node-swagger-proxy/tree/master/src/classes) to get an idea how to do this

**Comment by YujiaCheng1996** [comment]
Thanks. Our backend developers don't really want to do documents properly. Each one of them genrate a swagger seperately! Frontenders have no choice but merge them to a single one and use another tool to watch the differences periodically.

**Comment by ghost** [comment]
@YujiaCheng1996 

does this mean, anything works now as expected or do you still have some issues?
